plugins {
  id 'org.jetbrains.kotlin.multiplatform'
}

kotlin {
  macosArm64 {
    binaries {
      executable {
        entryPoint = 'app.cash.redwood.samples.gpui.main'
      }
    }
  }

  sourceSets {
    macosArm64Main {
      dependencies {
        implementation projects.redwoodHostGpui
        implementation projects.redwoodLayoutGpui
        implementation projects.redwoodUiBasicGpui
        implementation projects.redwoodLayoutApi
        implementation projects.redwoodUiBasicApi
        implementation projects.redwoodRuntime
      }
    }
  }
}
