import static app.cash.redwood.buildsupport.TargetGroup.Common
import static app.cash.redwood.buildsupport.DesktopTargets.Enable

redwoodBuild {
  targets(Common + Enable)
  publishing()
}

apply plugin: 'org.jetbrains.kotlin.multiplatform'
apply plugin: 'org.jetbrains.kotlin.plugin.serialization'

kotlin {
  sourceSets {
    commonMain {
      dependencies {
        implementation libs.kotlinx.serialization.core
        implementation projects.redwoodRuntime
      }
    }
  }
}
