import static app.cash.redwood.buildsupport.DesktopTargets.Enable
import static app.cash.redwood.buildsupport.TargetGroup.Common

redwoodBuild {
  targets(Common + Enable)
  publishing()
}

apply plugin: 'org.jetbrains.kotlin.multiplatform'
apply plugin: 'org.jetbrains.kotlin.plugin.serialization'

kotlin {
  sourceSets {
    commonMain {
      dependencies {
        implementation libs.kotlinx.serialization.core
      }
    }
  }
}
